// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/8/2026, 3:01:55 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/antonioortiz/Desktop/Antonio/obserbatorios/observatorio-techos-verdes/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/antonioortiz/Desktop/Antonio/obserbatorios/observatorio-techos-verdes/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/antonioortiz/Desktop/Antonio/obserbatorios/observatorio-techos-verdes/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/antonioortiz/Desktop/Antonio/obserbatorios/observatorio-techos-verdes/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/antonioortiz/Desktop/Antonio/obserbatorios/observatorio-techos-verdes/plugins/**/*.{js,ts,mjs}","/Users/antonioortiz/Desktop/Antonio/obserbatorios/observatorio-techos-verdes/composables/**/*.{js,ts,mjs}","/Users/antonioortiz/Desktop/Antonio/obserbatorios/observatorio-techos-verdes/utils/**/*.{js,ts,mjs}","/Users/antonioortiz/Desktop/Antonio/obserbatorios/observatorio-techos-verdes/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/antonioortiz/Desktop/Antonio/obserbatorios/observatorio-techos-verdes/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/antonioortiz/Desktop/Antonio/obserbatorios/observatorio-techos-verdes/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/antonioortiz/Desktop/Antonio/obserbatorios/observatorio-techos-verdes/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;